// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gcc_phat_run (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_in_TDATA,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TDATA,
        stream_out_TVALID,
        stream_out_TREADY
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] stream_in_TDATA;
input   stream_in_TVALID;
output   stream_in_TREADY;
output  [47:0] stream_out_TDATA;
output   stream_out_TVALID;
input   stream_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    stream_out_TDATA_blk_n;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire   [1:0] i_load_fu_282_p1;
reg   [1:0] i_reg_367;
wire    ap_CS_fsm_state10;
wire   [1:0] add_ln155_fu_291_p2;
reg   [1:0] add_ln155_reg_374;
wire   [63:0] zext_ln154_fu_297_p1;
reg   [63:0] zext_ln154_reg_379;
reg   [15:0] delays_data_load_reg_389;
wire    ap_CS_fsm_state21;
reg   [9:0] inputs_address0;
reg    inputs_ce0;
reg    inputs_we0;
wire   [15:0] inputs_q0;
reg   [9:0] inputs_1_address0;
reg    inputs_1_ce0;
reg    inputs_1_we0;
wire   [15:0] inputs_1_q0;
reg   [9:0] inputs_2_address0;
reg    inputs_2_ce0;
reg    inputs_2_we0;
wire   [15:0] inputs_2_q0;
reg   [9:0] inputs_3_address0;
reg    inputs_3_ce0;
reg    inputs_3_we0;
wire   [15:0] inputs_3_q0;
reg   [9:0] reference_M_real_address0;
reg    reference_M_real_ce0;
reg    reference_M_real_we0;
wire   [31:0] reference_M_real_q0;
reg   [9:0] reference_M_imag_address0;
reg    reference_M_imag_ce0;
reg    reference_M_imag_we0;
wire   [31:0] reference_M_imag_q0;
wire   [15:0] delays_data_q0;
wire   [1:0] delays_data_address1;
wire   [15:0] delays_data_q1;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_done;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_idle;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_ready;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_address0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_we0;
wire   [15:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_d0;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_address0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_we0;
wire   [15:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_d0;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_address0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_we0;
wire   [15:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_d0;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_address0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_we0;
wire   [15:0] grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_d0;
wire    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_stream_in_TREADY;
wire    grp_load_fu_218_ap_start;
wire    grp_load_fu_218_ap_done;
wire    grp_load_fu_218_ap_idle;
wire    grp_load_fu_218_ap_ready;
wire   [63:0] grp_load_fu_218_fft_stream_in_din;
wire    grp_load_fu_218_fft_stream_in_write;
wire   [9:0] grp_load_fu_218_src_address0;
wire    grp_load_fu_218_src_ce0;
reg   [15:0] grp_load_fu_218_src_q0;
reg    grp_fft_fft_params_s_fu_224_ap_ce;
wire    grp_fft_fft_params_s_fu_224_ap_start;
wire    grp_fft_fft_params_s_fu_224_ap_done;
wire    grp_fft_fft_params_s_fu_224_ap_idle;
wire    grp_fft_fft_params_s_fu_224_ap_ready;
wire    grp_fft_fft_params_s_fu_224_xn_read;
wire   [63:0] grp_fft_fft_params_s_fu_224_xk_din;
wire    grp_fft_fft_params_s_fu_224_xk_write;
wire   [7:0] grp_fft_fft_params_s_fu_224_status_data_V_din;
wire    grp_fft_fft_params_s_fu_224_status_data_V_write;
wire    grp_fft_fft_params_s_fu_224_config_ch_data_V_read;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_done;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_idle;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_ready;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_fft_stream_out_read;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_address0;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_we0;
wire   [31:0] grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_d0;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_address0;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_we0;
wire   [31:0] grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_d0;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_done;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_idle;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_ready;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_out_read;
wire   [63:0] grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_din;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_write;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_real_address0;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_real_ce0;
wire   [9:0] grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_imag_address0;
wire    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_imag_ce0;
wire    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start;
wire    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_done;
wire    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_idle;
wire    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_ready;
wire    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_fft_stream_out_read;
wire   [15:0] grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_index_out;
wire    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_index_out_ap_vld;
reg    grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_load_fu_218_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [7:0] fft_stream_config_din;
wire    fft_stream_config_full_n;
reg    fft_stream_config_write;
wire   [0:0] icmp_ln154_fu_285_p2;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
reg   [63:0] fft_stream_in_din;
wire    fft_stream_in_full_n;
reg    fft_stream_in_write;
reg    grp_fft_fft_params_s_fu_224_ap_start_reg;
wire   [63:0] fft_stream_in_dout;
wire    fft_stream_in_empty_n;
reg    fft_stream_in_read;
wire    fft_stream_out_full_n;
reg    fft_stream_out_write;
wire    fft_stream_status_full_n;
reg    fft_stream_status_write;
wire   [7:0] fft_stream_config_dout;
wire    fft_stream_config_empty_n;
reg    fft_stream_config_read;
reg    grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [7:0] fft_stream_status_dout;
wire    fft_stream_status_empty_n;
reg    fft_stream_status_read;
wire   [63:0] fft_stream_out_dout;
wire    fft_stream_out_empty_n;
reg    fft_stream_out_read;
wire    ap_CS_fsm_state9;
reg    grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    ap_block_state14_ignore_call3;
wire    ap_CS_fsm_state15;
reg    grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
reg   [1:0] i_2_fu_96;
reg    ap_predicate_op80_call_state11;
reg    ap_block_state11_on_subcall_done;
reg    ap_block_state1;
reg    ap_block_state14;
reg    delays_data_ce0_local;
reg   [1:0] delays_data_address0_local;
reg    delays_data_we0_local;
reg    delays_data_ce1_local;
wire    regslice_both_stream_out_V_data_V_U_apdone_blk;
reg    ap_block_state23;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    regslice_both_stream_in_V_data_V_U_apdone_blk;
wire   [63:0] stream_in_TDATA_int_regslice;
wire    stream_in_TVALID_int_regslice;
reg    stream_in_TREADY_int_regslice;
wire    regslice_both_stream_in_V_data_V_U_ack_in;
wire   [47:0] stream_out_TDATA_int_regslice;
reg    stream_out_TVALID_int_regslice;
wire    stream_out_TREADY_int_regslice;
wire    regslice_both_stream_out_V_data_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 23'd1;
#0 grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start_reg = 1'b0;
#0 grp_load_fu_218_ap_start_reg = 1'b0;
#0 grp_fft_fft_params_s_fu_224_ap_start_reg = 1'b0;
#0 grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start_reg = 1'b0;
#0 grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start_reg = 1'b0;
#0 grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start_reg = 1'b0;
#0 i_2_fu_96 = 2'd0;
end

gcc_phat_run_inputs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
inputs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputs_address0),
    .ce0(inputs_ce0),
    .we0(inputs_we0),
    .d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_d0),
    .q0(inputs_q0)
);

gcc_phat_run_inputs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
inputs_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputs_1_address0),
    .ce0(inputs_1_ce0),
    .we0(inputs_1_we0),
    .d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_d0),
    .q0(inputs_1_q0)
);

gcc_phat_run_inputs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
inputs_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputs_2_address0),
    .ce0(inputs_2_ce0),
    .we0(inputs_2_we0),
    .d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_d0),
    .q0(inputs_2_q0)
);

gcc_phat_run_inputs_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
inputs_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputs_3_address0),
    .ce0(inputs_3_ce0),
    .we0(inputs_3_we0),
    .d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_d0),
    .q0(inputs_3_q0)
);

gcc_phat_run_reference_M_real_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
reference_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(reference_M_real_address0),
    .ce0(reference_M_real_ce0),
    .we0(reference_M_real_we0),
    .d0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_d0),
    .q0(reference_M_real_q0)
);

gcc_phat_run_reference_M_real_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
reference_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(reference_M_imag_address0),
    .ce0(reference_M_imag_ce0),
    .we0(reference_M_imag_we0),
    .d0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_d0),
    .q0(reference_M_imag_q0)
);

gcc_phat_run_delays_data_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
delays_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(delays_data_address0_local),
    .ce0(delays_data_ce0_local),
    .we0(delays_data_we0_local),
    .d0(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_index_out),
    .q0(delays_data_q0),
    .address1(delays_data_address1),
    .ce1(delays_data_ce1_local),
    .q1(delays_data_q1)
);

gcc_phat_run_Pipeline_VITIS_LOOP_138_1 grp_run_Pipeline_VITIS_LOOP_138_1_fu_208(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start),
    .ap_done(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_done),
    .ap_idle(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_idle),
    .ap_ready(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_ready),
    .stream_in_TVALID(stream_in_TVALID_int_regslice),
    .inputs_3_address0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_address0),
    .inputs_3_ce0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_ce0),
    .inputs_3_we0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_we0),
    .inputs_3_d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_d0),
    .inputs_2_address0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_address0),
    .inputs_2_ce0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_ce0),
    .inputs_2_we0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_we0),
    .inputs_2_d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_d0),
    .inputs_1_address0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_address0),
    .inputs_1_ce0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_ce0),
    .inputs_1_we0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_we0),
    .inputs_1_d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_d0),
    .inputs_address0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_address0),
    .inputs_ce0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_ce0),
    .inputs_we0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_we0),
    .inputs_d0(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_d0),
    .stream_in_TDATA(stream_in_TDATA_int_regslice),
    .stream_in_TREADY(grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_stream_in_TREADY)
);

gcc_phat_load grp_load_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_fu_218_ap_start),
    .ap_done(grp_load_fu_218_ap_done),
    .ap_idle(grp_load_fu_218_ap_idle),
    .ap_ready(grp_load_fu_218_ap_ready),
    .fft_stream_in_din(grp_load_fu_218_fft_stream_in_din),
    .fft_stream_in_full_n(fft_stream_in_full_n),
    .fft_stream_in_write(grp_load_fu_218_fft_stream_in_write),
    .src_address0(grp_load_fu_218_src_address0),
    .src_ce0(grp_load_fu_218_src_ce0),
    .src_q0(grp_load_fu_218_src_q0)
);

gcc_phat_fft_fft_params_s grp_fft_fft_params_s_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_fft_fft_params_s_fu_224_ap_ce),
    .ap_start(grp_fft_fft_params_s_fu_224_ap_start),
    .ap_done(grp_fft_fft_params_s_fu_224_ap_done),
    .ap_idle(grp_fft_fft_params_s_fu_224_ap_idle),
    .ap_ready(grp_fft_fft_params_s_fu_224_ap_ready),
    .xn_dout(fft_stream_in_dout),
    .xn_empty_n(fft_stream_in_empty_n),
    .xn_read(grp_fft_fft_params_s_fu_224_xn_read),
    .xk_din(grp_fft_fft_params_s_fu_224_xk_din),
    .xk_full_n(fft_stream_out_full_n),
    .xk_write(grp_fft_fft_params_s_fu_224_xk_write),
    .status_data_V_din(grp_fft_fft_params_s_fu_224_status_data_V_din),
    .status_data_V_full_n(fft_stream_status_full_n),
    .status_data_V_write(grp_fft_fft_params_s_fu_224_status_data_V_write),
    .config_ch_data_V_dout(fft_stream_config_dout),
    .config_ch_data_V_empty_n(fft_stream_config_empty_n),
    .config_ch_data_V_read(grp_fft_fft_params_s_fu_224_config_ch_data_V_read)
);

gcc_phat_run_Pipeline_VITIS_LOOP_71_1 grp_run_Pipeline_VITIS_LOOP_71_1_fu_232(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start),
    .ap_done(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_done),
    .ap_idle(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_idle),
    .ap_ready(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_ready),
    .fft_stream_out_dout(fft_stream_out_dout),
    .fft_stream_out_empty_n(fft_stream_out_empty_n),
    .fft_stream_out_read(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_fft_stream_out_read),
    .reference_M_real_address0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_address0),
    .reference_M_real_ce0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_ce0),
    .reference_M_real_we0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_we0),
    .reference_M_real_d0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_d0),
    .reference_M_imag_address0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_address0),
    .reference_M_imag_ce0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_ce0),
    .reference_M_imag_we0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_we0),
    .reference_M_imag_d0(grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_d0)
);

gcc_phat_run_Pipeline_VITIS_LOOP_99_1 grp_run_Pipeline_VITIS_LOOP_99_1_fu_239(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start),
    .ap_done(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_done),
    .ap_idle(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_idle),
    .ap_ready(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_ready),
    .fft_stream_out_dout(fft_stream_out_dout),
    .fft_stream_out_empty_n(fft_stream_out_empty_n),
    .fft_stream_out_read(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_out_read),
    .fft_stream_in_din(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_din),
    .fft_stream_in_full_n(fft_stream_in_full_n),
    .fft_stream_in_write(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_write),
    .reference_M_real_address0(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_real_address0),
    .reference_M_real_ce0(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_real_ce0),
    .reference_M_real_q0(reference_M_real_q0),
    .reference_M_imag_address0(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_imag_address0),
    .reference_M_imag_ce0(grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_imag_ce0),
    .reference_M_imag_q0(reference_M_imag_q0)
);

gcc_phat_run_Pipeline_VITIS_LOOP_117_1 grp_run_Pipeline_VITIS_LOOP_117_1_fu_247(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start),
    .ap_done(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_done),
    .ap_idle(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_idle),
    .ap_ready(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_ready),
    .fft_stream_out_dout(fft_stream_out_dout),
    .fft_stream_out_empty_n(fft_stream_out_empty_n),
    .fft_stream_out_read(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_fft_stream_out_read),
    .index_out(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_index_out),
    .index_out_ap_vld(grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_index_out_ap_vld)
);

gcc_phat_fifo_w64_d1024_A fft_stream_in_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stream_in_din),
    .if_full_n(fft_stream_in_full_n),
    .if_write(fft_stream_in_write),
    .if_dout(fft_stream_in_dout),
    .if_empty_n(fft_stream_in_empty_n),
    .if_read(fft_stream_in_read)
);

gcc_phat_fifo_w64_d1024_A fft_stream_out_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_fft_params_s_fu_224_xk_din),
    .if_full_n(fft_stream_out_full_n),
    .if_write(fft_stream_out_write),
    .if_dout(fft_stream_out_dout),
    .if_empty_n(fft_stream_out_empty_n),
    .if_read(fft_stream_out_read)
);

gcc_phat_fifo_w8_d2_S fft_stream_config_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stream_config_din),
    .if_full_n(fft_stream_config_full_n),
    .if_write(fft_stream_config_write),
    .if_dout(fft_stream_config_dout),
    .if_empty_n(fft_stream_config_empty_n),
    .if_read(fft_stream_config_read)
);

gcc_phat_fifo_w8_d2_S fft_stream_status_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_fft_params_s_fu_224_status_data_V_din),
    .if_full_n(fft_stream_status_full_n),
    .if_write(fft_stream_status_write),
    .if_dout(fft_stream_status_dout),
    .if_empty_n(fft_stream_status_empty_n),
    .if_read(fft_stream_status_read)
);

gcc_phat_regslice_both #(
    .DataWidth( 64 ))
regslice_both_stream_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(stream_in_TDATA),
    .vld_in(stream_in_TVALID),
    .ack_in(regslice_both_stream_in_V_data_V_U_ack_in),
    .data_out(stream_in_TDATA_int_regslice),
    .vld_out(stream_in_TVALID_int_regslice),
    .ack_out(stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_V_data_V_U_apdone_blk)
);

gcc_phat_regslice_both #(
    .DataWidth( 48 ))
regslice_both_stream_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(stream_out_TDATA_int_regslice),
    .vld_in(stream_out_TVALID_int_regslice),
    .ack_in(stream_out_TREADY_int_regslice),
    .data_out(stream_out_TDATA),
    .vld_out(regslice_both_stream_out_V_data_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_data_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_fft_params_s_fu_224_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state6))) begin
            grp_fft_fft_params_s_fu_224_ap_start_reg <= 1'b1;
        end else if ((grp_fft_fft_params_s_fu_224_ap_ready == 1'b1)) begin
            grp_fft_fft_params_s_fu_224_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if (((~(i_load_fu_282_p1 == 2'd0) & ~(i_load_fu_282_p1 == 2'd1) & (icmp_ln154_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10)) | ((i_load_fu_282_p1 == 2'd0) & (icmp_ln154_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10)) | ((i_load_fu_282_p1 == 2'd1) & (icmp_ln154_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10)) | ((fft_stream_config_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_load_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_load_fu_218_ap_ready == 1'b1)) begin
            grp_load_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_ready == 1'b1)) begin
            grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start_reg <= 1'b1;
        end else if ((grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_ready == 1'b1)) begin
            grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start_reg <= 1'b0;
    end else begin
        if (((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start_reg <= 1'b1;
        end else if ((grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_ready == 1'b1)) begin
            grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state14_ignore_call3) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start_reg <= 1'b1;
        end else if ((grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_ready == 1'b1)) begin
            grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_2_fu_96 <= 2'd0;
    end else if ((~((1'b1 == ap_block_state11_on_subcall_done) | (fft_stream_config_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
        i_2_fu_96 <= add_ln155_reg_374;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln155_reg_374 <= add_ln155_fu_291_p2;
        i_reg_367 <= i_2_fu_96;
        zext_ln154_reg_379[1 : 0] <= zext_ln154_fu_297_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        delays_data_load_reg_389 <= delays_data_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state11_on_subcall_done) | (fft_stream_config_full_n == 1'b0))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_fft_params_s_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state14)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_fft_params_s_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((fft_stream_status_empty_n == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((stream_out_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state23)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((fft_stream_config_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_load_fu_218_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_fft_params_s_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((fft_stream_status_empty_n == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        delays_data_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        delays_data_address0_local = zext_ln154_reg_379;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        delays_data_address0_local = 64'd0;
    end else begin
        delays_data_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state10) | ((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state20)))) begin
        delays_data_ce0_local = 1'b1;
    end else begin
        delays_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        delays_data_ce1_local = 1'b1;
    end else begin
        delays_data_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        delays_data_we0_local = 1'b1;
    end else begin
        delays_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14))) begin
        fft_stream_config_din = 8'd0;
    end else if (((~((1'b1 == ap_block_state11_on_subcall_done) | (fft_stream_config_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | ((fft_stream_config_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        fft_stream_config_din = 8'd1;
    end else begin
        fft_stream_config_din = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        fft_stream_config_read = grp_fft_fft_params_s_fu_224_config_ch_data_V_read;
    end else begin
        fft_stream_config_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14)) | (~((1'b1 == ap_block_state11_on_subcall_done) | (fft_stream_config_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | ((fft_stream_config_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)))) begin
        fft_stream_config_write = 1'b1;
    end else begin
        fft_stream_config_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        fft_stream_in_din = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_din;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(i_reg_367 == 2'd0) & ~(i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11)) | ((i_reg_367 == 2'd0) & (1'b1 == ap_CS_fsm_state11)) | ((i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        fft_stream_in_din = grp_load_fu_218_fft_stream_in_din;
    end else begin
        fft_stream_in_din = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_din;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        fft_stream_in_read = grp_fft_fft_params_s_fu_224_xn_read;
    end else begin
        fft_stream_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        fft_stream_in_write = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_in_write;
    end else if (((1'b1 == ap_CS_fsm_state5) | (~(i_reg_367 == 2'd0) & ~(i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11)) | ((i_reg_367 == 2'd0) & (1'b1 == ap_CS_fsm_state11)) | ((i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        fft_stream_in_write = grp_load_fu_218_fft_stream_in_write;
    end else begin
        fft_stream_in_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        fft_stream_out_read = grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_fft_stream_out_read;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        fft_stream_out_read = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_fft_stream_out_read;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        fft_stream_out_read = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_fft_stream_out_read;
    end else begin
        fft_stream_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        fft_stream_out_write = grp_fft_fft_params_s_fu_224_xk_write;
    end else begin
        fft_stream_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14)) | ((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        fft_stream_status_read = 1'b1;
    end else begin
        fft_stream_status_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        fft_stream_status_write = grp_fft_fft_params_s_fu_224_status_data_V_write;
    end else begin
        fft_stream_status_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fft_fft_params_s_fu_224_ap_ce = 1'b1;
    end else begin
        grp_fft_fft_params_s_fu_224_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~(i_reg_367 == 2'd0) & ~(i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        grp_load_fu_218_src_q0 = inputs_3_q0;
    end else if (((i_reg_367 == 2'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        grp_load_fu_218_src_q0 = inputs_1_q0;
    end else if (((i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        grp_load_fu_218_src_q0 = inputs_2_q0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_load_fu_218_src_q0 = inputs_q0;
    end else begin
        grp_load_fu_218_src_q0 = 'bx;
    end
end

always @ (*) begin
    if (((i_reg_367 == 2'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        inputs_1_address0 = grp_load_fu_218_src_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_1_address0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_address0;
    end else begin
        inputs_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((i_reg_367 == 2'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        inputs_1_ce0 = grp_load_fu_218_src_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_1_ce0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_ce0;
    end else begin
        inputs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_1_we0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_1_we0;
    end else begin
        inputs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        inputs_2_address0 = grp_load_fu_218_src_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_2_address0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_address0;
    end else begin
        inputs_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        inputs_2_ce0 = grp_load_fu_218_src_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_2_ce0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_ce0;
    end else begin
        inputs_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_2_we0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_2_we0;
    end else begin
        inputs_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(i_reg_367 == 2'd0) & ~(i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        inputs_3_address0 = grp_load_fu_218_src_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_3_address0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_address0;
    end else begin
        inputs_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~(i_reg_367 == 2'd0) & ~(i_reg_367 == 2'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        inputs_3_ce0 = grp_load_fu_218_src_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_3_ce0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_ce0;
    end else begin
        inputs_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_3_we0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_3_we0;
    end else begin
        inputs_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        inputs_address0 = grp_load_fu_218_src_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_address0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_address0;
    end else begin
        inputs_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        inputs_ce0 = grp_load_fu_218_src_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_ce0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_ce0;
    end else begin
        inputs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        inputs_we0 = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_inputs_we0;
    end else begin
        inputs_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        reference_M_imag_address0 = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reference_M_imag_address0 = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_address0;
    end else begin
        reference_M_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        reference_M_imag_ce0 = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reference_M_imag_ce0 = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_ce0;
    end else begin
        reference_M_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        reference_M_imag_we0 = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_imag_we0;
    end else begin
        reference_M_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        reference_M_real_address0 = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reference_M_real_address0 = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_address0;
    end else begin
        reference_M_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        reference_M_real_ce0 = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_reference_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reference_M_real_ce0 = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_ce0;
    end else begin
        reference_M_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        reference_M_real_we0 = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_reference_M_real_we0;
    end else begin
        reference_M_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_TREADY_int_regslice = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_stream_in_TREADY;
    end else begin
        stream_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        stream_out_TDATA_blk_n = stream_out_TREADY_int_regslice;
    end else begin
        stream_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((stream_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        stream_out_TVALID_int_regslice = 1'b1;
    end else begin
        stream_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((fft_stream_config_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_load_fu_218_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_fft_fft_params_s_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln154_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((1'b1 == ap_block_state11_on_subcall_done) | (fft_stream_config_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_fft_fft_params_s_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_fft_fft_params_s_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((fft_stream_status_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((stream_out_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((1'b0 == ap_block_state23) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln155_fu_291_p2 = (i_2_fu_96 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state11_on_subcall_done = (((ap_predicate_op80_call_state11 == 1'b1) & (grp_load_fu_218_ap_done == 1'b0)) | ((i_reg_367 == 2'd0) & (grp_load_fu_218_ap_done == 1'b0)) | ((i_reg_367 == 2'd1) & (grp_load_fu_218_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state14 = ((fft_stream_status_empty_n == 1'b0) | (fft_stream_config_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state14_ignore_call3 = ((fft_stream_status_empty_n == 1'b0) | (fft_stream_config_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state23 = ((stream_out_TREADY_int_regslice == 1'b0) | (regslice_both_stream_out_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_predicate_op80_call_state11 = (~(i_reg_367 == 2'd0) & ~(i_reg_367 == 2'd1));
end

assign delays_data_address1 = 64'd1;

assign grp_fft_fft_params_s_fu_224_ap_start = grp_fft_fft_params_s_fu_224_ap_start_reg;

assign grp_load_fu_218_ap_start = grp_load_fu_218_ap_start_reg;

assign grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start = grp_run_Pipeline_VITIS_LOOP_117_1_fu_247_ap_start_reg;

assign grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start = grp_run_Pipeline_VITIS_LOOP_138_1_fu_208_ap_start_reg;

assign grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start = grp_run_Pipeline_VITIS_LOOP_71_1_fu_232_ap_start_reg;

assign grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start = grp_run_Pipeline_VITIS_LOOP_99_1_fu_239_ap_start_reg;

assign i_load_fu_282_p1 = i_2_fu_96;

assign icmp_ln154_fu_285_p2 = ((i_2_fu_96 == 2'd3) ? 1'b1 : 1'b0);

assign stream_in_TREADY = regslice_both_stream_in_V_data_V_U_ack_in;

assign stream_out_TDATA_int_regslice = {{{delays_data_q0}, {delays_data_q1}}, {delays_data_load_reg_389}};

assign stream_out_TVALID = regslice_both_stream_out_V_data_V_U_vld_out;

assign zext_ln154_fu_297_p1 = i_2_fu_96;

always @ (posedge ap_clk) begin
    zext_ln154_reg_379[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //gcc_phat_run
