// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gcc_phat_gcc_phat,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.203000,HLS_SYN_LAT=34951,HLS_SYN_TPT=34952,HLS_SYN_MEM=23,HLS_SYN_DSP=0,HLS_SYN_FF=26469,HLS_SYN_LUT=22680,HLS_VERSION=2025_1}" *)

module gcc_phat (
        stream_in_TDATA,
        stream_out_TDATA,
        ap_clk,
        ap_rst_n,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TVALID,
        stream_out_TREADY
);


input  [63:0] stream_in_TDATA;
output  [47:0] stream_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   stream_in_TVALID;
output   stream_in_TREADY;
output   stream_out_TVALID;
input   stream_out_TREADY;

 reg    ap_rst_n_inv;
wire    run_U0_ap_start;
wire    run_U0_ap_done;
wire    run_U0_ap_continue;
wire    run_U0_ap_idle;
wire    run_U0_ap_ready;
wire    run_U0_stream_in_TREADY;
wire   [47:0] run_U0_stream_out_TDATA;
wire    run_U0_stream_out_TVALID;

gcc_phat_run run_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(run_U0_ap_start),
    .ap_done(run_U0_ap_done),
    .ap_continue(run_U0_ap_continue),
    .ap_idle(run_U0_ap_idle),
    .ap_ready(run_U0_ap_ready),
    .stream_in_TDATA(stream_in_TDATA),
    .stream_in_TVALID(stream_in_TVALID),
    .stream_in_TREADY(run_U0_stream_in_TREADY),
    .stream_out_TDATA(run_U0_stream_out_TDATA),
    .stream_out_TVALID(run_U0_stream_out_TVALID),
    .stream_out_TREADY(stream_out_TREADY)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign run_U0_ap_continue = 1'b1;

assign run_U0_ap_start = 1'b1;

assign stream_in_TREADY = run_U0_stream_in_TREADY;

assign stream_out_TDATA = run_U0_stream_out_TDATA;

assign stream_out_TVALID = run_U0_stream_out_TVALID;

endmodule //gcc_phat
