-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gcc_phat is
port (
    stream_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_TVALID : IN STD_LOGIC;
    stream_in_TREADY : OUT STD_LOGIC;
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC );
end;


architecture behav of gcc_phat is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gcc_phat_gcc_phat,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s50-csga324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.971000,HLS_SYN_LAT=34935,HLS_SYN_TPT=34936,HLS_SYN_MEM=23,HLS_SYN_DSP=0,HLS_SYN_FF=25247,HLS_SYN_LUT=22338,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal run_U0_ap_start : STD_LOGIC;
    signal run_U0_ap_done : STD_LOGIC;
    signal run_U0_ap_continue : STD_LOGIC;
    signal run_U0_ap_idle : STD_LOGIC;
    signal run_U0_ap_ready : STD_LOGIC;
    signal run_U0_stream_in_TREADY : STD_LOGIC;
    signal run_U0_stream_out_TDATA : STD_LOGIC_VECTOR (47 downto 0);
    signal run_U0_stream_out_TVALID : STD_LOGIC;

    component gcc_phat_run IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        stream_in_TVALID : IN STD_LOGIC;
        stream_in_TREADY : OUT STD_LOGIC;
        stream_out_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
        stream_out_TVALID : OUT STD_LOGIC;
        stream_out_TREADY : IN STD_LOGIC );
    end component;



begin
    run_U0 : component gcc_phat_run
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => run_U0_ap_start,
        ap_done => run_U0_ap_done,
        ap_continue => run_U0_ap_continue,
        ap_idle => run_U0_ap_idle,
        ap_ready => run_U0_ap_ready,
        stream_in_TDATA => stream_in_TDATA,
        stream_in_TVALID => stream_in_TVALID,
        stream_in_TREADY => run_U0_stream_in_TREADY,
        stream_out_TDATA => run_U0_stream_out_TDATA,
        stream_out_TVALID => run_U0_stream_out_TVALID,
        stream_out_TREADY => stream_out_TREADY);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    run_U0_ap_continue <= ap_const_logic_1;
    run_U0_ap_start <= ap_const_logic_1;
    stream_in_TREADY <= run_U0_stream_in_TREADY;
    stream_out_TDATA <= run_U0_stream_out_TDATA;
    stream_out_TVALID <= run_U0_stream_out_TVALID;
end behav;
